using System;
using System.Numerics;

namespace ProjectEulerApp.Problems
{
    class Problem2 : IProblem
    {
        private string _name = "Problem 2";
        private string _title = "Even Fibonacci numbers";
        private string _description = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:"
            + Environment.NewLine + Environment.NewLine
            + "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..."
            + Environment.NewLine + Environment.NewLine
            + "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
        private string _requiredAnswer = "4613732";
        private BigInteger _myAnswer;
        public string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        public string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        public string Title
        {
            get { return _title; }
            set { _title = value; }
        }

        public string RequiredAnswer
        {
            get { return _requiredAnswer; }
            set { _requiredAnswer = value; }
        }

        public BigInteger MyAnswer
        {
            get { return _myAnswer; }
            set { _myAnswer = value; }
        }

        public BigInteger GetAnswer()
        {
            int x = 2;
            int OldX = 1;
            int OldOldX = 1;
            int sum = 0;
            while (x < 4000000)
            {
                if (x % 2 == 0)
                {
                    sum += x;
                }
                OldOldX = OldX;
                OldX = x;
                x = (OldOldX + OldX);
            }

            return sum;
        }
    }
}
