using System;
using System.Numerics;

namespace ProjectEulerApp.Problems
{
    class Problem44 : UtilityMethods, IProblem
    {
        private string _name = "Problem 44";
        private string _title = "Pentagon numbers";
        private string _description = "Pentagonal numbers are generated by the formula, Pₙ=n(3n−1)/2. The first ten pentagonal numbers are:"
            + Environment.NewLine + Environment.NewLine
            + "        1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ..."
            + Environment.NewLine + Environment.NewLine
            + "It can be seen that P₄ + P₇ = 22 + 70 = 92 = P₈.However, their difference, 70 − 22 = 48, is not pentagonal."
            + Environment.NewLine + Environment.NewLine
            + "Find the pair of pentagonal numbers, Pⱼ and Pₖ, for which their sum and difference are pentagonal and D = | Pₖ − Pⱼ| is minimised; what is the value of D?";
        string _requiredAnswer = "5482660";
        private BigInteger _myAnswer;

        public string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        public string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        public string Title
        {
            get { return _title; }
            set { _title = value; }
        }

        public string RequiredAnswer
        {
            get { return _requiredAnswer; }
            set { _requiredAnswer = value; }
        }

        public BigInteger MyAnswer
        {
            get { return _myAnswer; }
            set { _myAnswer = value; }
        }

        public BigInteger GetAnswer()
        {
            BigInteger answer = 0;
            bool notFound = true;
            int i = 1;

            while (notFound)
            {
                i++;
                int n = i * (3 * i - 1) / 2;

                for (int j = i - 1; j > 0; j--)
                {
                    int m = j * (3 * j - 1) / 2;
                    if (IsPentagonal(n - m) && IsPentagonal(n + m))
                    {
                        answer = Math.Abs(n - m);
                        notFound = false;
                        break;
                    }
                }
            }

            return answer;
        }
    }
}
